# -*- coding: utf-8 -*-
"""chap5ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJyQWyCAg92u4DY3vpbbl_fbNKcsAhyJ
"""

prog_words = {
    'variables': "Containers for storing values",
    'constants': "Fixed variables",
    'concatenation': "Adding strings together",
    'string': "A series of characters",
    'list': "Collection of items in a particular order"
}
print("\nVariables: " + prog_words['variables'] + ".")
print("\nConstants: " + prog_words['constants'] + ".")
print("\nConcatenation: " + prog_words['concatenation'] + ".")
print("\nString: " + prog_words['string'] + ".")
print("\nList: " + prog_words['list'] + ".")
