# -*- coding: utf-8 -*-
"""chap5ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJyQWyCAg92u4DY3vpbbl_fbNKcsAhyJ
"""

person = {'first_name': 'Railey', 'last_name': 'Inductivo', 'age': '17', 'city': 'Dubai'}
print("First name:", person['first_name'])
print("Last name:", person['last_name'])
print("Age:", person['age'])
print("City:", person['city'])